# Generated by Django 4.0 on 2022-01-17 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("auth", "0012_alter_user_first_name_max_length")]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated date"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="auth.user",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "Customer"),
                            ("SELLER", "Seller"),
                        ],
                        default="CUSTOMER",
                        max_length=21,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
