version: '3.7'

services:

  postgres:
    container_name: shop_db
    image: postgis/postgis:13-3.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"

  pgadmin:
    container_name: shop_pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5080:80"
